PACA-516 (DRAFT): Add FI_DOC_CLM_CNTL_NUM and CARR_CLM_CNTL_NUM definitions
CMSgov/bluebutton-site-static pull request #261
Opened 2022-04-08 18:51 UTC by KyRobbins

**JIRA Ticket:**
[PACA-516](https://jira.cms.gov/browse/PACA-516)

**User Story or Bug Summary:**

### What Does This PR Do?

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

* TODO

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies? **Yes** or **No**.
    * Does this PR modify or invalidate any of our security controls? **Yes** or **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **Yes** or **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **Yes** or **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

* CMSgov/some_repo#42

### Submitter Checklist

I have gone through and verified that...:

* [ ] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [ ] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [ ] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [ ] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2022-04-08 21:30 UTC, ericbuckley commented on _layouts/basic.html
> +    <script src="https://unpkg.com/feather-icons"></script>
whats the feather library used for?

2022-04-11 16:37 UTC, KyRobbins commented on _layouts/basic.html
> +    <script src="https://unpkg.com/feather-icons"></script>
This appears to be used to pull in SVG images to be used within the page layout.

2022-04-11 22:33 UTC, ericbuckley requested changes
based on the information we discovered today, both of these URLs will need to be under the `/resources/variables` path so they are backwards compatible with the coding systems already in use in the v1 EOBs

2022-04-12 18:20 UTC, ericbuckley commented on _pages/resources-variables-fi_doc_clm_cntl_num.md
> +- **Source:** FISS
```suggestion
- **Source:** CCW
```

2022-04-12 18:20 UTC, ericbuckley commented on _pages/resources-variables-carr_clm_cntl_num.md
> +- **Source:** MCS
```suggestion
- **Source:** CCW
```

2022-04-12 18:21 UTC, ericbuckley approved these changes

2022-04-14 19:10 UTC, brianburton approved these changes

2022-04-15 16:06 UTC, micahtaylor commented
Per discussion with @ericbuckley I added in the 404 page title to the 404 page as well to help with Google Analytics reporting.

2022-04-15 16:16 UTC, micahtaylor commented on _layouts/basic.html
> +    <script src="https://unpkg.com/feather-icons"></script>
Yup. Lib used for icons.

2022-04-15 16:17 UTC, micahtaylor approved these changes
Looks good. I will squash and merge and deploy on Monday.

2022-04-15 16:17 UTC, merged