heading hierarchy and formatting updates on developers.md
CMSgov/bluebutton-site-static pull request #303
Opened 2023-04-06 19:04 UTC by gmaciolek

**JIRA Ticket:**
[BB2-2169](https://jira.cms.gov/browse/BB2-2169)

**User Story or Bug Summary:**

The heading structure on the static site documentation does not adhere to best practices for writing for the web or accessibility. Formatting issues cause the page to be difficult to scan.

- The top-level headings are h3s and should be h2s
- Subheadings should be nested under h2s
- Bolded text is used instead of headings in several places
- Bolded text is used too much, causing visual clutter and making the content hierarchy difficult to decipher at-a-glance
- Code formatting is not used in places where it should be
- Numbered lists in the "Try the API" section have padding issues, formatting issues, and restart their numbering partway through
- Images have inconsistent padding

### What Does This PR Do?

- Fixes heading hierarchy issues
- Fixes issues with numbered lists in "Try the API" section
- Fixes image display and padding issues
- Fixes overuse of bold text
- Adds code formatting to content that should be formatted as code

### What Should Reviewers Watch For?

- Any content changes made as part of this PR were to help resolve content hierarchy issues. The substance of the content remains the same.
- The padding fix for images uses inline css, which is not an ideal solution, but there aren't very many screenshots and it's a temporary fix while we work on the updating the content

If you're reviewing this PR, please check these things, in particular:

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies?  **No**.
    * Does this PR modify or invalidate any of our security controls? **No**.
    * Does this PR store or transmit data that was not stored or transmitted before?   **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?   **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

* CMSgov/some_repo#42

### Submitter Checklist

I have gone through and verified that...:

* [x ] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x ] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [x ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x ] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [ x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [x ] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2023-04-06 20:48 UTC, mrengy commented on _pages/developers.md
>  **FHIR Resources:**
I see you corrected this in several places, but here it's still using bold rather than a heading - I think this should be an h3 rather than bold. Same for a few pseudo-headings below.

2023-04-06 20:52 UTC, mrengy commented on _pages/developers.md
Same issue on the line above (can't comment on that line for some reason) "Patient FHIR Resource" should be an h3 rather than bold

2023-04-06 20:52 UTC, mrengy commented on _pages/developers.md
"Coverage FHIR Resource" should be an h3 rather than bold

2023-04-06 20:54 UTC, mrengy commented on _pages/developers.md
> +**Query by Type Examples**
Maybe "query by type examples" should be an h5 rather than bold - if we're going all the way down to h5

2023-04-06 20:56 UTC, mrengy commented on _pages/developers.md
>  | v2 | `https://sandbox.bluebutton.cms.gov/v2/fhir/ExplanationOfBenefit/?type=inpatient` <br />Or<br /> `https://sandbox.bluebutton.cms.gov/v2/fhir/ExplanationOfBenefit/?type=https://bluebutton.cms.g
"carrier claims" and "inpatient claims" should be h5 rather than bold - if we're going all the way down to h5

2023-04-06 20:56 UTC, mrengy commented on _pages/developers.md
> +**PDE Claims**
"PDE Claims" should be an h5 rather than bold - if we're going all the way down to h5

2023-04-06 20:59 UTC, mrengy commented on _pages/developers.md
"FHIR Bundle example" should be h4 rather than bold

2023-04-06 21:00 UTC, mrengy commented on _pages/developers.md
"Bundle navigation example" should be h4 rather than bold

2023-04-06 21:00 UTC, mrengy commented on _pages/developers.md
"Patient identifier example" should be h4 rather than bold.

2023-04-06 21:02 UTC, mrengy commented on _pages/developers.md
"Meet Lucille" and "Meet Jack" should be h3 rather than bold

2023-04-06 21:02 UTC, mrengy commented on _pages/developers.md
>  **Migrating to v2/FHIR R4 FAQ**
"Migrating to v2/FHIR R4 FAQ" Should be h3 rather than bold

2023-04-06 21:03 UTC, mrengy commented on _pages/developers.md
"Where can you find the latest information?" should be h3 rather than bold

2023-04-06 21:21 UTC, mrengy requested changes
This is a lot of tedious formatting! Okay, I made some inline comments where there are some things that I think still should be converted from bold to headings. 

Also I pushed a couple of formatting commits on this branch - they're captured in this pull request so will be incorporated when merged.

2023-04-07 16:37 UTC, dtisza1 requested changes
@gmaciolek These changes are looking great! I had a few change requests, if they make sense to you.

To review, I looked at this PR branch locally. Then compared side-by-side with the current static site and changes to the markdown in the file. I was mostly focused on the formatting.

The new version is looking much better! I really like that the headings are more consistent on the page. While reviewing, the changes Mike suggested are sounding good to me too.

Thank you for the awesome work on this!

2023-04-07 16:37 UTC, dtisza1 commented on _pages/developers.md
> +| v1 | `curl --header "Authorization: Bearer AUTHORIZATION TOKEN" "https://sandbox.bluebutton.cms.gov/v1/connect/userinfo"` |
```suggestion
| v1 | `curl --header "Authorization: Bearer <AUTHORIZATION TOKEN>" "https://sandbox.bluebutton.cms.gov/v1/connect/userinfo"` |
```
Same here as previous, if you agree.

2023-04-07 16:37 UTC, dtisza1 commented on _pages/developers.md
> +| v2 | `curl --header "Authorization: Bearer AUTHORIZATION TOKEN" "https://sandbox.bluebutton.cms.gov/v2/connect/userinfo"` |
```suggestion
| v2 | `curl --header "Authorization: Bearer <AUTHORIZATION TOKEN>" "https://sandbox.bluebutton.cms.gov/v2/connect/userinfo"` |
```

2023-04-07 16:37 UTC, dtisza1 commented on _pages/developers.md
> +The FHIR ID for this beneficiary is `-20140000000024`
```suggestion
The PATIENT ID for this beneficiary is `-20140000000024`
```
I think patient id is better to use in our docs.

2023-04-07 17:02 UTC, gmaciolek commented on _pages/developers.md
I'm going to unbold this instead of making it a heading. This follows the pattern of other sections like "Consuming the Data."

2023-04-07 17:03 UTC, gmaciolek commented on _pages/developers.md
I'm going to unbold this instead of making it a heading. This follows the pattern of other sections like "Consuming the Data."

2023-04-07 17:03 UTC, gmaciolek commented on _pages/developers.md
I'm going to unbold this instead of making it a heading. This follows the pattern of other sections like "Consuming the Data."

2023-04-07 17:50 UTC, dtisza1 approved these changes
Looks good to me!

Great work on this!

2023-04-10 15:28 UTC, mrengy approved these changes

2023-04-10 15:29 UTC, mrengy commented
Fixes look good to me as well!

2023-04-11 14:17 UTC, merged