BB2 2241 Update developers.md with new Authorization section content
CMSgov/bluebutton-site-static pull request #312
Opened 2023-06-08 15:07 UTC by gmaciolek

Updated Authorization section with new up-to-date content

**JIRA Ticket:**
[BB2-2241](https://jira.cms.gov/browse/BB2-2241)

**User Story or Bug Summary:**

Updated version of current Authorization section for developers integrating with BB2.0 API.

### What Does This PR Do?

* Updates Authorization section content
* Removes Beneficiary Revoking Access subheading and content under Developer guidelines
* 
### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:
* Verify that all code samples in the Authorization section are formatted properly and are accurate

* Links: 
  * check that all links in Authorization section work
  * check that external links open in new tab
  * check that internal links stay in new tab

* Tables in the Authorization section should be formatted properly--like the other tables in the documentation with borders

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies?  **No**.
    * Does this PR modify or invalidate any of our security controls? **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

### Submitter Checklist

I have gone through and verified that...:

* [x ] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x ] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [ x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [ x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x ] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [x ] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2023-06-09 14:03 UTC, ajshred commented on _pages/developers.md
> +### <a id="register-application"></a> Step 1: Join the developer sandbox and register a sandbox application
I assume this wasn't intended?

2023-06-09 14:09 UTC, ajshred commented on _pages/developers.md
> +The Blue Button API supports the [OAuth 2.0 Authorization Framework](https://tools.ietf.org/html/rfc6749){:target="_blank"} using the [authorization code grant](https://www.rfc-editor.org/rfc/rfc6749
This external link does not open in a new tab.

2023-06-09 14:44 UTC, ajshred requested changes
Just 3 minor items to address.

2023-06-09 14:54 UTC, gmaciolek commented on _pages/developers.md
> +### <a id="register-application"></a> Step 1: Join the developer sandbox and register a sandbox application
It was intended, but I forgot that I did it! I wanted an easy way to link to this section in the beginning of the Authorization section where we say, "To initiate an integration, you'll need the client ID and client secret for your application that were generated when you [registered your application](https://github.com/CMSgov/bluebutton-site-static/blob/7323fc6b1e5c8863f5f7620f14e4056776df980e/_pages/developers.md#register-application)."

2023-06-09 16:36 UTC, ajshred approved these changes
Looks good!  Thanks Gretchen!!!

2023-06-09 19:34 UTC, dtisza1 requested changes
@gmaciolek This is looking good.

Had a few change requests.

We should double check the change suggestions after they are rendered.

Sorry that some of the changes got missed in the confluence doc review. 

Thank you!

2023-06-09 19:34 UTC, dtisza1 commented on _pages/developers.md
> +-d "code=TSjqiZCdJwGyytGjz2GzziPfHTJ6z2&grant_type=authorization_code&redirect_uri=http://localhost/testclient/callback](http://localhost/testclient/callback)"
```suggestion
-d "code=TSjqiZCdJwGyytGjz2GzziPfHTJ6z2&grant_type=authorization_code&redirect_uri=http://localhost:8080/testclient/callback"
```

2023-06-09 19:34 UTC, dtisza1 commented on _pages/developers.md
> +* `grant_type`: `refresh_token`
I think should add this too?

```suggestion
* `grant_type`: `refresh_token`
* `refresh_token`
```

2023-06-09 19:34 UTC, dtisza1 commented on _pages/developers.md
> +-u "swBu7LWsCnIRfu530qnfPw1y5vMmER3lAM2L6rq2:\<client_secret\>" \
Backslashes should be removed.

```suggestion
-u "swBu7LWsCnIRfu530qnfPw1y5vMmER3lAM2L6rq2:<client_secret>" \
```

2023-06-09 19:34 UTC, dtisza1 commented on _pages/developers.md
> +-u "swBu7LWsCnIRfu530qnfPw1y5vMmER3lAM2L6rq2:\<client_secret\>" \
Should remove the backslashes here.

```suggestion
-u "swBu7LWsCnIRfu530qnfPw1y5vMmER3lAM2L6rq2:<client_secret>" \
```

2023-06-09 19:34 UTC, dtisza1 commented on _pages/developers.md
> +#### Common access token errors
Should change this, since a `refresh` token usage referenced.

```suggestion
#### Common token endpoint errors
```

2023-06-15 20:40 UTC, gmaciolek commented
@dtisza1 Thanks for catching all those little details! I had to clean up a bunch of garbage characters going from Confluence to Markdown, so I'm not surprised I missed a few. I committed all your change requests.

2023-06-16 13:35 UTC, dtisza1 approved these changes
@gmaciolek This looks good to me!

2023-06-16 13:42 UTC, merged