BB2-3179: Update developer documentation for expired data grant
CMSgov/bluebutton-site-static pull request #357
Opened 2024-05-29 19:25 UTC by stiwarisemanticbits

**JIRA Ticket:**
[BB2-3179](https://jira.cms.gov/browse/BB2-3179)

**User Story or Bug Summary:**

### What Does This PR Do?
Update developer documentation for expired data grant for application. This PR lists error which we get while refreshing token with expired data grant

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

* TODO

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies? **Yes** or **No**.
    * Does this PR modify or invalidate any of our security controls? **Yes** or **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **Yes** or **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **Yes** or **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

* CMSgov/some_repo#42

### Submitter Checklist

I have gone through and verified that...:

* [ ] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [ ] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [ ] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [ ] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2024-05-31 15:06 UTC, loganbertram requested changes
I left a comment on a typo and a suggestion for rewording one sentence. Everything else looks great!

2024-05-31 15:06 UTC, loganbertram commented on _pages/developers.md
> +If the authorization for accessing user data by an application has expired, the corresponding access token will not be able to be refreshed. Attempts to refresh that token will result in the followin
Two quick notes. First, "Grant" is misspelled "Gramt" in the title. Second, did the text here come from somewhere or does it have or need product review? I might reword the first bit to "If an application's authorization for accessing user data has expired..." That's just a suggestion though.

2024-06-03 18:14 UTC, loganbertram approved these changes

2024-06-03 18:27 UTC, jimmyfagan commented on _pages/developers.md
> +}
This content is good, but it's inconsistent with the other examples in this section. Could you update the above examples so there is more consistency in the included information (i.e. include error descriptions in the output for the other cases too)?

2024-06-03 20:27 UTC, jimmyfagan commented on _pages/developers.md
> +}
Discussed offline, those other cases are accurate, just happens that those other scenarios do not have an error description and status code included in the response.

2024-06-03 20:40 UTC, jimmyfagan approved these changes
One last unrelated fix suggested in my comments, but this looks good otherwise, thanks!

2024-06-03 20:40 UTC, jimmyfagan commented on _pages/developers.md
> +-H “Content-Length: 0"
```suggestion
-H "Content-Length: 0"
```

2024-06-03 20:49 UTC, jimmyfagan approved these changes

2024-06-03 21:34 UTC, merged