BB2-3390: Implement privacy modal
CMSgov/bluebutton-site-static pull request #386
Opened 2024-11-06 14:41 UTC by loganbertram

**JIRA Ticket:**
[BB2-BB2-3390](https://jira.cms.gov/browse/BB2-3390)

### What Does This PR Do?

Implements the tealium gdpr privacy modal as on AB2D.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

Currently, tealium tags need to be updated before merging this PR. This complicates local testing as well, though it is possible for the time being to swap out the tags locally to ones with the correct version.

### Validation

Currently, this can be validated by swapping the tealium tags specified in the code (which point to version controlled tags in Akamai) with versions implemented by AB2D: https://tealium-tags.cms.gov/cms-innovations/prod/utag.sync.js and https://tealium-tags.cms.gov/cms-ab2d/prod/utag.js. Testing may wait until additional tealium updates to simplify this effort or we can jumpstart testing by manually swapping the tags on lines 40-60 of _includes/head.html

### What Security Implications Does This PR Have?

Please indicate if this PR does any of the following:

* Adds any new software dependencies
* Modifies any security controls
* Adds new transmission or storage of data
* Any other changes that could possibly affect security?

- [ ] Yes, one or more of the above security implications apply. This PR must not be merged without the ISSO or team security engineer's approval.

2024-11-06 15:10 UTC, loganbertram commented
Temporarily set this to draft until tealium tags are updated

2024-11-13 19:28 UTC, loganbertram commented on _includes/head.html
> +{% if site.tealium_env == "prod" %}
Sloppy conditionals here, but limited by jekyll rendering inside the script tag. Otherwise, we'd use the tealium env variable.

2024-11-19 23:01 UTC, jimmyfagan requested changes
Based on discussion on [this ticket](https://jira.cms.gov/browse/BLSTANALYT-10298) and documentation at [this page](https://confluence.cms.gov/display/BLSTANALYT/Tealium+Implementation+Documentation), the utag.js script needs to be added to the `body` not the `head`, as is seen in the attached screenshot. 
<img width="780" alt="image" src="https://github.com/user-attachments/assets/9e03c61a-e36e-41fc-a751-cf7aa6cd1b70">
The utag.sync.js script can stay on the `head`. I may be misunderstanding something, so if there are any doubts about what we should be doing here, you should probably try to huddle with Joshua to get on the same page here, maybe even demoing what you see locally.

2024-11-20 20:03 UTC, jimmyfagan approved these changes
Based on the latest from Joshua, I think we can move forward here and just confirm with Blast team during deployment rollout.

2024-11-20 20:07 UTC, bwang-icf approved these changes

2024-11-26 17:07 UTC, merged

2024-11-26 17:56 UTC, loganbertram commented
Ah! I thought those approvals were new. I actually didn't move the sync injection point, which is still in the header on l30. I'm not sure why it's now rendering that in its current position unless something about the sync.js impacts where it is ultimately inserted.

2024-11-26 18:03 UTC, jimmyfagan commented
I think the line that adds the sync is just the `<script src="{{ site.tealium_url }}"></script>` which somewhere in the last two commits was moved from head.html to footer.html. I'd need to see it in action to confirm, but I think moving that line back to where it was is all we need here.